defaults:
  - L_small_full
  - _self_

name: L_small_medium

density_channel_config:
  clip_percentile: [0.001, 0.999]
  fit_mask_percentile: 0.003
  enabled_channels:
  # 老的 40 通道
  - "exp_nonorm_nopost"
  - "exp_nonorm_gauss1"
  - "exp_nonorm_gauss2"
  - "exp_nonorm_DoG1"
  - "exp_nonorm_DoG2"
  - "exp_clipnorm_nopost"
  - "exp_clipnorm_gauss1"
  - "exp_clipnorm_gauss2"
  - "exp_clipnorm_DoG1"
  - "exp_clipnorm_DoG2"
  - "sim_nonorm_nopost"
  - "sim_nonorm_gauss1"
  - "sim_nonorm_gauss2"
  - "sim_nonorm_DoG1"
  - "sim_nonorm_DoG2"
  - "sim_clipnorm_nopost"
  - "sim_clipnorm_gauss1"
  - "sim_clipnorm_gauss2"
  - "sim_clipnorm_DoG1"
  - "sim_clipnorm_DoG2"
  - "diff_nonorm_nopost"
  - "diff_nonorm_gauss1"
  - "diff_nonorm_gauss2"
  - "diff_nonorm_DoG1"
  - "diff_nonorm_DoG2"
  - "diff_clipnorm_nopost"
  - "diff_clipnorm_gauss1"
  - "diff_clipnorm_gauss2"
  - "diff_clipnorm_DoG1"
  - "diff_clipnorm_DoG2"
  - "posdiff_nonorm_nopost"
  - "posdiff_nonorm_gauss1"
  - "posdiff_nonorm_gauss2"
  - "posdiff_nonorm_DoG1"
  - "posdiff_nonorm_DoG2"
  - "posdiff_clipnorm_nopost"
  - "posdiff_clipnorm_gauss1"
  - "posdiff_clipnorm_gauss2"
  - "posdiff_clipnorm_DoG1"
  - "posdiff_clipnorm_DoG2"
