# @package model
backbone:
  pseudo_atom_cfg:
    base_count: 64
    scale_factor: 0.3
    max_sample_rounds: 3
    init_feat_mode: "zero"
    init_feat_noise_std: 0.0
    neighbor_radius: 3.0
    enable_density_weighting: true
    density_channel_index: 0
    density_prob_base: 0.1
    delete_too_close_radius: 1.5
    delete_too_far_radius: 8.0
    lifecycle: [false, true, true]
