defaults:
  - dense
  - _self_



name: sparse


backbone:
  voxel_backbone:
    return_feature_keys: ["voxel_c4", "voxel_final"]

  point_fusion_map:
    point_enc2: null
    point_enc3: null
    point_enc4: voxel_c4
    point_feat: voxel_final

  point_fusion_modes: ["concat_linear", "concat_linear"]
  sampler_modes: ["trilinear", "trilinear"]
