# @package model
backbone:
  point_backbone:
    _target_: src.model.stage1_point_backbone.Stage1PointBackbone
    backend: zeros                 # str, 全零占位模式
    atom_feature_dim: 49
    point_grid_size: 0.25
    input_embed_dim: 64
    input_embed_hidden_dim: 128
    out_channels: 64
    recycle_feature_dim: 64
