# 主配置入口点 (Main Configuration Entry Point)

defaults:
  - sparse_h100
  - override train: default_h200
  - override model: dense
  - override dataset: unfused
  - _self_






name: dense_unfused_h200
tag: "密集_非融合"
project_name: PV_dense_unfused


