from __future__ import annotations

from pathlib import Path


DEFAULT_RAW_JSON = Path("/home/penghongen/My_Project/Data/raw.json")
DEFAULT_PARSED_ROOT = Path("/home/penghongen/My_Project/Data/DATA_v2_raw4/parsed_pdb")
DEFAULT_OUTPUT_ROOT = Path("/storage/penghongen/CIF_Ligand")

TARGET_LIGAND_CLASS_ID = 4

COORD_MEDIAN_THRESHOLD = 0.05
COORD_MAX_THRESHOLD = 0.20

RCSB_FULL_CIF_URL = "https://files.rcsb.org/download/{pdb_id}.cif"
RCSB_CHEMCOMP_URL = "https://data.rcsb.org/rest/v1/core/chemcomp/{ccd_id}"
RCSB_LIGAND_MOL2_URL = (
    "https://models.rcsb.org/v1/{pdb_id}/ligand"
    "?auth_seq_id={pdb_seq_num}&label_asym_id={label_asym_id}"
    "&encoding=mol2&filename={filename}"
)

PASS_HIGH = "PASS_HIGH"
SKIPPED_NON_SMALL_MOLECULE = "SKIPPED_NON_SMALL_MOLECULE"
RAW_JSON_PDB_NOT_IN_PARSED_ROOT = "RAW_JSON_PDB_NOT_IN_PARSED_ROOT"
PDB_LEVEL_FAILED = "PDB_LEVEL_FAILED"
RCSB_INSTANCE_MATCH_FAILED = "RCSB_INSTANCE_MATCH_FAILED"
RCSB_CHEMCOMP_DOWNLOAD_FAILED = "RCSB_CHEMCOMP_DOWNLOAD_FAILED"
RCSB_SMILES_MISSING = "RCSB_SMILES_MISSING"
RCSB_NATIVE_MOL2_MISSING = "RCSB_NATIVE_MOL2_MISSING"
VALIDATION_FAILED = "VALIDATION_FAILED"

FORMAT_OK = "FORMAT_OK"
FORMAT_OK_WITH_WARNING = "FORMAT_OK_WITH_WARNING"
FORMAT_OK_FOR_LIBRARY_ENTRY = "FORMAT_OK_FOR_LIBRARY_ENTRY"
FORMAT_OK_SMILES_AND_STRUCTURE = "FORMAT_OK_SMILES_AND_STRUCTURE"
NOT_READY_NO_VALID_NATIVE_MOL2_PAIR = "NOT_READY_NO_VALID_NATIVE_MOL2_PAIR"
NOT_READY_NO_VALID_SMILES_OR_STRUCTURE = "NOT_READY_NO_VALID_SMILES_OR_STRUCTURE"
